import { Karla } from "next/font/google";
import "./globals.css";

const karla = Karla({
  weight: ["400", "700"], // Specify desired font weights
  subsets: ["latin"], // Specify language subsets if needed
});

export const metadata = {
  title: "Single Price Grid",
  description: "Generated by Heejung Hong",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="bg-light-gray flex items-center justify-center h-screen"
    >
      <body className={`${karla.variable}`}>{children}</body>
    </html>
  );
}
